service: movie-api

provider:
  name: google
  runtime: nodejs
  project: general-192213
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/huey.json

  memorySize: 256
  timeout: 90s

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - yarn-error.log

functions:
  CommonSenseMedia:
    handler: CommonSenseMedia
    events:
      - http: path
  RottenTomatoes:
    handler: RottenTomatoes
    events:
      - http: path
  OMDb:
    handler: OMDb
    events:
      - http: path
  Moowee:
    handler: Moowee
    events:
      - http: path
